//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_CV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutRight
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Descript { get; set; }
    }
}
