//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_CV.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Portfolio_Db : DbContext
    {
        public Portfolio_Db()
            : base("name=Portfolio_Db")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutLeft> AboutLefts { get; set; }
        public virtual DbSet<AboutRight> AboutRights { get; set; }
        public virtual DbSet<ContactInfo> ContactInfoes { get; set; }
        public virtual DbSet<Header> Headers { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<PortfolioDown> PortfolioDowns { get; set; }
        public virtual DbSet<PortfolioUp> PortfolioUps { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Sosial> Sosials { get; set; }
    }
}
